import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  header: {
    height: 90,
    paddingBottom: 12,
    paddingTop: 30,
    backgroundColor: '#0d4f8c',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
    zIndex: 3,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 6,
    borderBottomWidth: 2,
    borderBottomColor: '#0a3d70',
  },
  headerTitleContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '700',
    textAlign: 'center',
    letterSpacing: 0.8,
    textShadowColor: 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  hamburger: {
    position: 'absolute',
    left: 12,
    width: 44,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    zIndex: 1,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  hamburgerContainer: {
    width: 24,
    height: 18,
    justifyContent: 'space-between',
  },
  hamburgerLines: {
    width: 24,
    height: 3,
    backgroundColor: '#fff',
    borderRadius: 2,
  },
  content: {
    flex: 1,
    backgroundColor: '#f8fafc',
    padding: 12,
    paddingTop: 14,
    zIndex: 0,
  },
  contentDisabled: {
    opacity: 1,
  },
  footer: {
    minHeight: 64,
    backgroundColor: '#ffffff',
    borderTopWidth: 1.5,
    borderTopColor: '#e2e8f0',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    zIndex: 3,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  footerContent: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  footerText: {
    color: '#475569',
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 2,
    letterSpacing: 0.3,
  },
  footerSubText: {
    color: '#94a3b8',
    fontSize: 10,
    fontWeight: '500',
    letterSpacing: 0.2,
  },
  menuOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-start',
    zIndex: 9998,
    elevation: 9998,
  },
  menuPanelContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    width: '100%',
    justifyContent: 'flex-start',
    zIndex: 9999,
    elevation: 9999,
  },
  menuPanel: {
    width: '72%',
    maxWidth: 300,
    backgroundColor: '#ffffff',
    flex: 1,
    marginTop: 90,
    shadowColor: '#0f172a',
    shadowOffset: { width: 4, height: 0 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 10,
    borderRightWidth: 1.5,
    borderRightColor: '#e2e8f0',
  },
  menuHeader: {
    paddingVertical: 20,
    paddingHorizontal: 16,
    borderBottomWidth: 1.5,
    borderBottomColor: '#e2e8f0',
    backgroundColor: '#f1f5f9',
  },
  menuHeaderTitle: {
    fontWeight: '700',
    fontSize: 20,
    color: '#0d4f8c',
    marginBottom: 4,
    letterSpacing: -0.3,
  },
  menuHeaderSubtitle: {
    fontSize: 12,
    color: '#475569',
    fontWeight: '500',
    letterSpacing: 0.2,
  },
  menuItem: {
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderRadius: 0,
    marginBottom: 2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    position: 'relative',
  },
  menuItemPressed: {
    backgroundColor: '#f3f4f6',
  },
  menuItemActive: {
    backgroundColor: '#0d4f8c',
  },
  menuItemText: {
    fontSize: 16,
    color: '#475569',
    fontWeight: '600',
    letterSpacing: -0.2,
  },
  menuItemTextActive: {
    color: '#fff',
    fontWeight: '700',
    letterSpacing: -0.2,
  },
  menuItemIndicator: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 4,
    backgroundColor: '#fff',
  },
});

export default styles;
