import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  header: {
    height: 90,
    paddingBottom: 12,
    paddingTop: 30,
    backgroundColor: '#07305a',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
    zIndex: 3,
  },
  headerTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '800',
    position: 'absolute',
    left: 0,
    right: 0,
    textAlign: 'center',
  },
  hamburger: {
    position: 'absolute',
    left: 12,
    width: 66,
    height: 66,
    justifyContent: 'center',
    alignItems: 'center',
  },
  hamburgerLines: {
    width: 30,
    height: 4,
    backgroundColor: '#fff',
    marginVertical: 2,
    borderRadius: 2,
  },
  content: {
    flex: 1,
    backgroundColor: '#f5f6f8',
    padding: 12,
    paddingTop: 14,
  },
  footer: {
    height: 64,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#e6e6e6',
    alignItems: 'center',
    justifyContent: 'center',
    paddingBottom: 12,
    zIndex: 3,
  },
  footerText: {
    color: '#666',
    fontSize: 12,
  },
  menuOverlay: {
    position: 'absolute',
    top: 90,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'flex-start',
    zIndex: 1,
  },
  menuPanelContainer: {
    position: 'absolute',
    top: 90,
    left: 0,
    bottom: 0,
    width: '100%',
    justifyContent: 'flex-start',
    zIndex: 2,
  },
  menuPanel: {
    width: '72%',
    maxWidth: 300,
    backgroundColor: '#fff',
    paddingVertical: 20,
    paddingHorizontal: 12,
    flex: 1,
  },
  menuItem: {
    paddingVertical: 16,
    paddingHorizontal: 12,
    borderRadius: 6,
    marginBottom: 8,
  },
  menuItemText: {
    fontSize: 16,
    color: '#072b4b',
    fontWeight: '600',
  },
});

export default styles;
